DB_USER=${POSTGRES_USER:=tuhlmann}
DB_PASSWORD="${POSTGRES_PASSWORD:=tuhlmann}"
DB_NAME="${POSTGRES_DB:=newsletter}"
DB_PORT="${POSTGRES_PORT:=5432}"

export DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@localhost:${DB_PORT}/${DB_NAME}